version: '3.8'

services:
  pg:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=bestbooks
      - POSTGRES_USER=geaglts
      - POSTGRES_PASSWORD=geaglts
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=geaglts@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=geaglts
